### ISSUE TITLE
hgetall fails on key with large number of fields

### ISSUE THREAD

**Issue by nsheard** [vert-x/mod-redis#26]
Hi,

I've run into an issue with mod-redis 1.1.4 where if I attempt to do a hgetall on a key with a large number of fields it fails with various exceptions.  I initially saw the issue in some code with only about 15 fields, but have written this test code that demonstrates the issue:

```
final String testKey = "testKey";
JsonObject command = new JsonObject();
command.putString("command", "hmset");

JsonArray args = new JsonArray();
args.add(testKey);
for (int i=0; i<100; i++) {
    args.add("field"+i);
    args.add("1234567890");
}
command.putArray("args", args);
			    
vertx.eventBus().send("my.redis", command, new Handler<Message<JsonObject>>() {
    @Override
    public void handle(Message<JsonObject> result) {
        //key should be stored
					
        //now hgetall the key
        JsonObject command = new JsonObject();
        JsonArray args = new JsonArray();
        args.add(testKey);
        command.putString("command", "hgetall");
        command.putArray("args", args);
					    
        vertx.eventBus().send("my.redis", command, new Handler<Message<JsonObject>>() {
            @Override
            public void handle(Message<JsonObject> result) {
                //never get here - lots of exceptions output instead!!!
            }
        });
    }
});
```

The exact number of fields that it fails at seems to vary.  The exceptions generated are along the lines of:
```
SEVERE: Exception in Java verticle
java.lang.IndexOutOfBoundsException: index: 2049 (expected: range(0, 2048))
	at io.netty.buffer.AbstractByteBuf.checkIndex(AbstractByteBuf.java:1118)
	at io.netty.buffer.AbstractByteBuf.getByte(AbstractByteBuf.java:331)
	at io.netty.buffer.WrappedByteBuf.getByte(WrappedByteBuf.java:205)
	at org.vertx.java.core.buffer.Buffer.getByte(Buffer.java:115)
	at io.vertx.redis.ReplyParser.parseResult(ReplyParser.java:100)
	at io.vertx.redis.ReplyParser.handle(ReplyParser.java:141)
	at io.vertx.redis.ReplyParser.handle(ReplyParser.java:7)
	at org.vertx.java.core.net.impl.DefaultNetSocket.handleDataReceived(DefaultNetSocket.java:237)
	at org.vertx.java.core.net.impl.VertxNetHandler.channelRead(VertxNetHandler.java:47)
	at org.vertx.java.core.net.impl.VertxNetHandler.channelRead(VertxNetHandler.java:31)
	at org.vertx.java.core.net.impl.VertxHandler.channelRead(VertxHandler.java:155)
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:338)
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:324)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:126)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:485)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:452)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:346)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101)
	at java.lang.Thread.run(Thread.java:722)
```
followed by several along the lines of:
```
SEVERE: Exception in Java verticle
java.lang.RuntimeException: Received a non pub/sub message without reply handler waiting:field69
	at io.vertx.redis.RedisConnection.handleReply(RedisConnection.java:262)
	at io.vertx.redis.ReplyParser.handle(ReplyParser.java:147)
	at io.vertx.redis.ReplyParser.handle(ReplyParser.java:7)
	at org.vertx.java.core.net.impl.DefaultNetSocket.handleDataReceived(DefaultNetSocket.java:237)
	at org.vertx.java.core.net.impl.VertxNetHandler.channelRead(VertxNetHandler.java:47)
	at org.vertx.java.core.net.impl.VertxNetHandler.channelRead(VertxNetHandler.java:31)
	at org.vertx.java.core.net.impl.VertxHandler.channelRead(VertxHandler.java:155)
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:338)
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:324)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:126)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:485)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:452)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:346)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101)
	at java.lang.Thread.run(Thread.java:722)
```
I've tried re-writing the code using RedisClient and experience the same issue.

Looks to me like the response from Redis is being broken up into several messages and not handled correctly (just a guess).

Any suggestions would be greatly appreciated as without this working I'm not going to be able to use mod-redis.

Many Thanks

**Comment by elad-yosifon** [comment]
I'm having similar issues...
my pre-condition is:  
using the hgetall command on a remote redis server (i.e. not localhost) with a greater latency rate than the rate of executing the command...   
e.g. : sending hgetall every 100ms ... and the full response takes more than 100ms to arrive (or related to pipelining)..

I think it's happening because of the way you are using the Buffer object in ReplyParser class to handle the async inputs...

**Comment by smiklosovic** [comment]
why have you closed this?

**Comment by pmlopes** [comment]
Because the issue is not reproducible, if you can provide an working example showing it I will investigate further.

**Comment by smiklosovic** [comment]
Interesting approach ... the fact it is not reproducible by you does not mean that it is eligible for closing. Once closed, once somebody hits the same issue and visits this project, it is possible he does not find it among open ones hence the submits another one.

however ... your project, your issues :)

**Comment by purplefox** [comment]
It's a prerequisite for any issue that it needs to be reproducible and 
the onus is on the person who reported the issue to provide a reproducer.

This is not something specific to Vert.x, it's a completely standard 
approach used by any project I have worked on in the last 20 years. 
You'd be hard pushed to find a high profile project that does not do 
this. Including JBoss, Eclipse, Apache, Oracle, SpringSource, Pivotal etc

**Comment by purplefox** [comment]
If the issue can be reproduced, the issue can be-opened. Closed issues do not "disappear".

**Comment by pmlopes** [comment]
@smiklosovic 9 months ago there was a test added to the project with the details of this issue, the test passes on our machines and also on the CI environment, there isn't much more I can do unless someone provides a different reproducer:

https://github.com/vert-x/mod-redis/blob/master/mod/src/test/java/io/vertx/redis/Issue26.java

If the issue affects you, please update the test to show the bug and then I can investigate further, otherwise it is like a needle on a haystack
